### ISSUE TITLE
[Servers only] Create items use IE plates in recipes instead of sheets

### ISSUE THREAD

**Issue by theboo** [NillerMedDild/Enigmatica5#357] opened 2020-06-17 00:31 UTC
**Modpack version**
0.5.0

**Issue**
so anything in create that takes a sheet in its recipe uses an IE plate instead. There is a sheet to plate recipe, but it is fairly annoying to have to do every time. IDK if this is intentional or not.. i know i could just get a bit of IE set up but that's not the point haha, ruins the flow of create a bit having to throw other mods in to a system very early in the mod

edit: this issue only seems to be present on servers, in single player it cycles between the sheets and the plates

https://gyazo.com/d94484ab4eb59329a18a00b86bccaed8

screenshot not super helpful but in single player those IE gold plates cycle to Create gold sheets, on the server they do not

**Comment by NielsPilgaard** [comment] 2020-06-17 08:13
I'll get that fixed :) thanks!

**Comment by NielsPilgaard** [comment] 2020-06-20 19:12
Hmm I can't reproduce this on a server in 0.5.1

**Comment by NielsPilgaard** [comment] 2020-06-20 19:12
Will close it for now, can always re-open if need be :)

**Comment by theboo** [comment] 2020-06-26 02:53
On official server, check recipes for Create wrench, goggles, propeller, mechanical saw, mechanical plough, rope pulley, mechanical harvester, superglue, whisk, copper casing, and copper shingles. Seems like anything that would take a create sheet material that has a matching IE plate(gold, iron and copper) has broken recipes on the official server not letting us use the sheets(the recipes only accept IE plates). In single player it cycles through the sheets and plates in JEI.

**Comment by theboo** [comment] 2020-06-26 05:11
Not just on the official server either, i notice the same issues on my personal server. And I dont think it is my client as i am using a separate instance when i log in to my server as i have Create Integrations installed

**Comment by theboo** [comment] 2020-06-26 05:18
Actually, looking now, it seems i was mistaken when i said it only happens on servers... When i tested single player before i must have been looking at something that uses a brass sheet which does not have an IE equivalent.

**Comment by NielsPilgaard** [comment] 2020-06-26 07:08
Probably another race condition, I can't reproduce it on servers or Singleplayer ><

**Comment by Frikkle** [comment] 2020-06-26 08:12
Boo, are you running the stock pack or do you have stuff added on top of that?

**Comment by Frikkle** [comment] 2020-06-26 08:12
I'll try and reproduce the issue later today.

**Comment by theboo** [comment] 2020-06-26 20:20
Stock pack when I play on the official server...  And the only difference on my personal server is create integrations added... But I see the issue on both as well as single player on both instances, not at home to screenshot/record rn to prove I am not crazy xD

**Comment by NielsPilgaard** [comment] 2020-06-26 20:49
I misunderstood the issue, sheets aren't even supposed to be obtainable, that's the issue :P Re-opened here #379

**Closed as completed by NielsPilgaard** 2020-06-26 20:49 UTC
Labels: Status: Won't Fix
