### ISSUE TITLE
Mining Gadget Laser not centered on block. 

### ISSUE THREAD

**Issue by Zymm2133** [NillerMedDild/Enigmatica5#312] opened 2020-05-15 05:42 UTC
**Modpack version**
0.4.11

**Issue**
Mining Gadget Laser not centered on block. 
![mining beam](https://user-images.githubusercontent.com/65385723/82015573-aba6cf80-9644-11ea-84e5-fccdb0ed4880.png)
![mining beam 2](https://user-images.githubusercontent.com/65385723/82015654-e7419980-9644-11ea-992c-c033e0f5db37.png)

**Logs**
Input pastebin link to crash-report or latest log, if applicable

**Comment by Zymm2133** [comment] 2020-05-15 05:59
Tested on 2 different systems, one using a texture pack and one not.

**Comment by hvdklauw** [comment] 2020-05-15 13:42
Yeah, same here.. also structurize building wand preview is like 1.5 blocks offset from where it's actually placing things.

I think this was already in 0.4.10, then I had some weird things too

**Comment by NielsPilgaard** [comment] 2020-05-15 13:46
Thank you for the report, I will investigate the issue.

**Comment by NielsPilgaard** [comment] 2020-05-15 20:20
~~I removed ShetiPhianCore and MultiBeds, and the problem went poof.~~
I commented on the wrong issue, still investigating this one.

**Comment by Zymm2133** [comment] 2020-05-15 23:50
Awesome.  Thank you for the info.

-Ben
________________________________

**Comment by Zymm2133** [comment] 2020-05-16 01:58
That didn’t work on my system. Removed mods from server and client.

-Ben
________________________________

**Comment by NielsPilgaard** [comment] 2020-05-16 05:02
Try reading my comment again :P

**Comment by Zymm2133** [comment] 2020-05-16 13:44
Sorry I missed that last part.   :)

**Comment by NielsPilgaard** [comment] 2020-05-17 19:21
The issue seems to have been caused by the mod Neat, it is now fixed.

**Comment by hvdklauw** [comment] 2020-05-17 19:52
Neat :trollface:

**Comment by Darkere** [comment] 2020-05-22 13:43
More reports of this. Even with the new Neat version :/

**Comment by NielsPilgaard** [comment] 2020-05-22 16:49
Yay another one of those issues, it works just fine for me :P

**Comment by NielsPilgaard** [comment] 2020-05-22 17:30
Still works just fine for me, do you have any more details @Darkere?

**Comment by xenoflot** [comment] 2020-05-24 22:23
I was getting this with Enig5 and ATM5 packs, for Powah, Building Gadgets and Minecolonies previews. I updated to the latest alpha Enig5 (which presumably includes Neat 1.6-22) and my previews are now all where they're supposed to be. Neat's health bars are even above heads instead of tickling knees!

**Comment by hvdklauw** [comment] 2020-05-25 06:15
Fixed in 0.4.13 after following the instructions to delete certain folders before updating

**Closed as completed** 2020-05-25 06:41 UTC
Labels: Status: Fixed In Next Release, Mod Issue
