### ISSUE TITLE
Silver ore enriching makes wrong type of silver dust

### ISSUE THREAD

**Issue by Giovanni-NL** [NillerMedDild/Enigmatica5#315] opened 2020-05-19 10:47 UTC
**Modpack version**
0.4.10

**Issue**
Using a Mekanism enriching factory to process silents_mechanisms:silver_ore produces occultism:silver_dust which cannot be processed by a Mekanism smelting factory, breaking the logical flow of ore processing.

To fix this I see 2 options.
1) Change the output of the enriching recipe to silents_mechanisms:silver_dust, or
2) Allow the Mekanism smelting machines to process occultism:silver_dust.

**Logs**
n.a.

**Comment by NielsPilgaard** [comment] 2020-05-19 11:33
Option 3: Update to 0.4.12 :P
Edit: Please let me know if that resolves the issue.
Edit2: Did you see errors in the chat when you logged in?

**Comment by Giovanni-NL** [comment] 2020-05-19 14:52
![image](https://user-images.githubusercontent.com/4085882/82341607-f2a01680-99f0-11ea-875b-11add32fb8fd.png)
These are all the messages I get when logging in. Does not seem to be related to this issue.  I'll let you know the results of 0.4.12 once we updated the server.

**Comment by Giovanni-NL** [comment] 2020-05-19 15:01
Ok, this issue just got weird.  We restarted the 0.4.10 server, and this time when you process the same type of silver ore in an enriching factory it produces the correct silents_mechanisms:silver_dust which can be processed further.  I have no clue what happened here, but it looks like a server restart fixed the issue...

**Comment by NielsPilgaard** [comment] 2020-05-19 15:02
That message is very much related to the issue, it means the scripts have failed to load - Meaning the scripts that fix processing recipes aren't active.

**Comment by Giovanni-NL** [comment] 2020-05-19 15:11
[crafttweaker.log](https://github.com/NillerMedDild/Enigmatica5/files/4651337/crafttweaker.log)
Don't know if this still is needed, but this server logfile contains the error I see in the client.

**Comment by NielsPilgaard** [comment] 2020-05-19 15:12
That is to be expected, but thank you - This issue may have been fixed in 0.4.12 but I can't test it, so please let me know if you encounter it again :)

**Comment by AndromeHyperion** [comment] 2020-05-19 15:20
Might be something to note,

I play on the same server, i've logged in with the 0.4.12 client after the restart of the server, for me it started to work.

If i start up my 0.4.10 profile and try the same thing in a single player world the issue is there.

**Comment by NielsPilgaard** [comment] 2020-05-19 15:46
Good sign, I really hope it's fixed :D

**Comment by theboo** [comment] 2020-05-19 19:21
vroooooom

**Comment by NielsPilgaard** [comment] 2020-05-20 15:42
Any update? :)

**Comment by Giovanni-NL** [comment] 2020-05-20 16:00
We just updated the server to 0.4.12
No more error messages in chat when logging in, so scripts seem to be all active.
Also, silver ore now processes in to silent's mechanisms dusts which can be smelted.
Problem solved I would say.

**Comment by Giovanni-NL** [comment] 2020-05-22 17:19
I've asked the server owner to send me those logs.  They're too large to copy/paste via the terminal window that I have access to.  I'll keep you posted.

**Comment by NielsPilgaard** [comment] 2020-05-22 17:21
Thank you - FYI a restart almost always fixes it. Temporarily of course ^^'

**Comment by Giovanni-NL** [comment] 2020-05-22 20:07
[crafttweaker.log](https://github.com/NillerMedDild/Enigmatica5/files/4670145/crafttweaker.log)
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4670146/latest.log)
And here they are

**Comment by NielsPilgaard** [comment] 2020-05-22 20:09
Huh, there aren't really any errors specific to this issue in there O_O

**Comment by Giovanni-NL** [comment] 2020-05-22 20:11
Yeah, only strange thing I see is that occultism_ore_inot_crushing is spelled with inot instead of ingot

**Comment by NielsPilgaard** [comment] 2020-05-22 20:12
Myeah but that's just a typo, I copy-pasted the typo to the place I'm calling it so no problem :P

**Comment by NielsPilgaard** [comment] 2020-05-22 20:12
Did you restart the server, and did that resolve it for now?

**Comment by Darkere** [comment] 2020-05-22 20:13
Errors are in the latest.log around line 3365.

Not sure if those are actual errors or not :/

**Comment by Giovanni-NL** [comment] 2020-05-22 20:14
Nope, will do that now, and do some tests

**Comment by NielsPilgaard** [comment] 2020-05-22 20:16
CrT always prints that stuff though.

**Comment by Giovanni-NL** [comment] 2020-05-22 20:22
Restarted the server, logged back in, grabbed some silent_mechanisms:silver_ore, but it keeps outputting occultism:silver_dust in the Enrichment Factory.

**Comment by Giovanni-NL** [comment] 2020-05-22 20:26
[latest.log](https://github.com/NillerMedDild/Enigmatica5/files/4670207/latest.log)
[crafttweaker.log](https://github.com/NillerMedDild/Enigmatica5/files/4670209/crafttweaker.log)
And the log files from since that restart

**Comment by NielsPilgaard** [comment] 2020-05-22 20:30
At long last, I think I understand what's going on here. Please try deleting the openloader and kubejs folders from the server, and replace them with ones from a fresh install of the pack. Doesn't matter if you grab the folders from server or client :)

**Comment by Giovanni-NL** [comment] 2020-05-22 20:32
hmm, ok. Will give that a go

**Comment by NielsPilgaard** [comment] 2020-05-22 20:35
Thank you, and sorry for the hassle :)

**Comment by Giovanni-NL** [comment] 2020-05-22 20:35
No problem, never mind a bit of bug hunting

**Comment by Giovanni-NL** [comment] 2020-05-22 20:48
Nope, makes no difference.  I emptied out those two folders on the server, and uploaded the files from my 0.4.12 client to those folders.  All this with the server stopped.  I did a file compare, and the files are all identical, so makes sense the symptoms are the same.  I'm now going to download a fresh copy of the pack and use the files from there. See if that does make a difference.

**Comment by NielsPilgaard** [comment] 2020-05-22 20:49
I did say a fresh install. Your client files would have the same issue.

**Comment by Giovanni-NL** [comment] 2020-05-22 20:55
Yeah, reading is hard, I know :P However, when I download the server zip, and do a binary compare of the contents of those two folders kubejs and openloader are exactly the same.  Zip content, current client folders and current server folders are all the same. No differences there.  Still, I'm going to delete my 0.4.12 client, and install from scratch. See what magic happens then.

**Comment by NielsPilgaard** [comment] 2020-05-22 20:56
Oh. Well that's not good news ><

**Comment by Giovanni-NL** [comment] 2020-05-22 21:12
Ok, first impressions. Just managed to win a wrestling match with the Twitch client, and finally got a fresh install of the 0.4.12 client.  Comparing that to the 0.4.12 server files from the zip does show quite a few differences between client and server files.  Dunno if that's good or bad... 
![image](https://user-images.githubusercontent.com/4085882/82709738-90117980-9c81-11ea-84d5-d37e6a48137f.png)
Left is the installed client, right the server zip file.  Going to start things up and see what happens.

**Comment by Giovanni-NL** [comment] 2020-05-22 21:16
Aaaargh. For some reason I have client 0.4.9
That did not go as planned

**Comment by Giovanni-NL** [comment] 2020-05-22 21:23
![image](https://user-images.githubusercontent.com/4085882/82710397-11b5d700-9c83-11ea-99c0-15fe8bb39e83.png)
This is more like it.  Correct client version this time.  As you can see, all files in those folders are identical, except for 2 empty folders that only exist in the server zip.

**Comment by NielsPilgaard** [comment] 2020-05-22 21:25
Well shit ><

**Comment by Giovanni-NL** [comment] 2020-05-22 21:26
Yeah, I'm starting the server now, but I don't expect this to be the fix

**Comment by NielsPilgaard** [comment] 2020-05-22 21:27
Nope, I'll keep trying to find the issue ^^'

**Comment by Giovanni-NL** [comment] 2020-05-22 21:42
This is driving me nuts.  Copied those files from the fresh client install to the server. Started everything up, and now the correct dust comes out of the enrichment factory.  I'm going to keep an eye out and wait for this to go wrong again, and then hopefully be able to backtrack to what might trigger the switch to the incorrect silver dust type.

**Comment by NielsPilgaard** [comment] 2020-05-22 21:48
Thank you :)

In the mean time, I'm going to make an occultism:silver_dust -> silver ingot furnace recipe :P

**Comment by MuteTiefling** [comment] 2020-05-23 18:56
Currently playing 0.4.12 and am having the same issue. 

Mekanism 3x processing is giving me jaopca clumps from silver ore as expected, then dirty jaopca as expected, but enrichment gives me occultism silver dust, which has no uses other than to hand craft to Silent's silver. It can't be smelted, and therefore gums up the mekanism processing line.

**Comment by NielsPilgaard** [comment] 2020-05-23 19:27
If you're playing on a server, restarting it can fix it. If singleplayer, same thing.

**Comment by NielsPilgaard** [comment] 2020-05-24 19:06
![billede](https://user-images.githubusercontent.com/21295394/82762621-55831a80-9e02-11ea-82d5-1ac070722b61.png)
I did a thing. Please let me know how 0.4.13 works for you, I still can't reproduce the issue.

**Comment by NielsPilgaard** [comment] 2020-05-24 19:43
I'm going to close this issue for the sake of changelog generation, but please comment here if it's still an issue. Or even if you can confirm that it isn't, that would be nice :P

**Closed as completed by NielsPilgaard** 2020-05-24 19:43 UTC
Labels: Bug, Status: Fixed In Next Release
