### ISSUE TITLE
Quark Stone Brick Variants Unobtainable 

### ISSUE THREAD

**Issue by merlerm** [NillerMedDild/Enigmatica5#510] opened 2020-09-29 11:46 UTC
**Modpack version**
0.6.0

**Issue**
The brick variations of the quark stones (only those native to quark) are uncraftable right now. They could be added to the stonecutter.

**Comment by NielsPilgaard** [comment] 2020-09-29 14:34
sorta duplicate of #508, thanks though, will get that fixed.

**Comment by merlerm** [comment] 2020-09-29 14:41
my bad, i didn't check at all for open issues

**Closed as completed** 2020-10-06 18:39 UTC
Labels: Bug, Status: Fixed In Next Release
