### ISSUE TITLE
No oregen in specific biomes

### ISSUE THREAD

**Issue by Dournbrood** [NillerMedDild/Enigmatica5#458] opened 2020-08-05 14:38 UTC
**Modpack version**
0.5.5

**Issue**
Integrated Dynamics biomes generate no ores nor any structures of any kind. This is probably intended by the mod, but is still a major game balance issue. Normally this would be a non-issue but MineColonies is in the pack. Once a village is set up, it's not possible for players to change/move them without access to commands. This is problematic for no-cheat survival/hardcore or servers. Without mods that can generate their own resources, MineColonies may be the primary source of ore income for most players and a village that can't mine ores is functionally dead.

**Comment by NielsPilgaard** [comment] 2020-08-05 18:07
Duplicate of #427

**Closed as completed by NielsPilgaard** 2020-08-05 18:07 UTC
Labels: Duplicate
