### ISSUE TITLE
Zero-Tick ghost Blocks

### ISSUE THREAD

**Issue by creepystalker2** [NillerMedDild/Enigmatica5#220] opened 2020-04-23 02:39 UTC
I am using a contraption on the server that makes use of zero-tick pulses. I had the chunk it was in loaded, and left the area. When I came back, several pistons and blocks had vanished. They behave like air blocks, except pistons cannot push them, gravity blocks land on top of them, and no blocks can be placed where they are. I have relogged and reloaded the chunks, and the issue persists. I am currently trying to reproduce the issue in a singleplayer test world.

**Comment by theboo** [comment] 2020-04-23 03:29
caused by ftb claims, pistons moving so fast it thinks you werent the one who placed it and it removes the block

**Comment by creepystalker2** [comment] 2020-04-23 03:31
Still no way to fix the ghost block once they appear, and still makes zero-tick mechanics incompatible with claiming chunks, which is a large thing to work around.

**Comment by NielsPilgaard** [comment] 2020-04-23 05:49
Reported to the author on Discord.

**Comment by NielsPilgaard** [comment] 2020-04-23 17:56
We're a few versions behind, should be fixed :)

**Closed as completed** 2020-04-23 20:03 UTC
Labels: Status: Fixed In Next Release, Mod Issue
