### ISSUE TITLE
No Loot in Chests

### ISSUE THREAD

**Issue by Zamar037** [NillerMedDild/Enigmatica5#188] opened 2020-04-14 21:03 UTC
**Modpack version**
Version 0.4.1

**Issue**
All chests that would contain loot are completely empty. This includes the bonus chest if you choose it at world creation; as well as mineshafts. I'm assuming the same would be for all other loot chests that can be found in vanilla structures (dungeons, desert temple, villages, jungle temple, etc)

**Logs**
n/a

**Comment by NielsPilgaard** [comment] 2020-04-14 21:07
Thank you for the report, I will investigate the issue.

**Comment by theboo** [comment] 2020-04-15 20:13
can confirm at least abandoned mine shaft mine-cart chests are empty

**Comment by Zamar037** [comment] 2020-04-15 22:19
Update: I've gone out further in a copy of my world in creative mode and found chests with loot inside. It may be that chests within initial spawning area on world creation yields empty chests.

**Comment by theboo** [comment] 2020-04-16 23:07
nah, ive found chests all over... vanilla dungeons 5k blocks from spawn and minecart chests in mineshafts both empty... havent found a minecart chest with items yet and ive done tons of exploring looking for apotheosis bosses

**Comment by NielsPilgaard** [comment] 2020-04-17 20:26
I was unable to reproduce this in a fresh BoP world.

**Comment by NielsPilgaard** [comment] 2020-04-17 20:31
I'm going to go ahead and call this fixed by updating some mod between 0.4.1 and 0.4.3, please reopen if I'm wrong :)

**Closed as completed by NielsPilgaard** 2020-04-17 20:31 UTC
Labels: Bug, Status: Fixed In Next Release
